chore: edit values file for new server options specification
SwissDataScienceCenter/renku pull request #2121
Opened 2021-05-12 15:29 UTC by olevski

Depends on https://github.com/SwissDataScienceCenter/renku-notebooks/pull/649 and should be merged together with https://github.com/SwissDataScienceCenter/renku-notebooks/pull/649

2021-05-17 13:09 UTC, aledegano approved these changes

2021-05-18 12:23 UTC, ableuler requested changes
Good description of the new value, I'd just try to avoid duplication.

2021-05-18 12:23 UTC, ableuler commented on helm-chart/values.yaml.changelog.md
> +* NEW *notebooks.serverDefaults* has been added with default values that will be
I'd try to keep this short and just link to the new section in the chart readme that you also add: https://github.com/SwissDataScienceCenter/renku/tree/master/helm-chart#upgrading-to-08x (I know it's a bit annoying to make those links ahead of time for unreleased tags)

2021-06-03 08:15 UTC, rokroskar commented
@olevski @ableuler does this need to go in asap?

2021-06-03 15:52 UTC, ableuler commented
> @olevski @ableuler does this need to go in asap?

No. It should be merged once we do the next release in the notebooks-service and bump the corresponding chart requirement.

2021-10-04 14:40 UTC, closed without merging