WIP: K8s operator POC
SwissDataScienceCenter/renku pull request #2142
Opened 2021-05-28 16:32 UTC by olevski

2021-06-29 16:30 UTC, ableuler commented
/deploy renku-notebooks=k8s-operator-poc

@olevski is that already expected to work? anyway... I'm feeling lucky :)

2021-06-30 13:15 UTC, olevski commented
> > /deploy renku-notebooks=k8s-operator-poc
> 
> @olevski is that already expected to work? anyway... I'm feeling lucky :)

It will not work because I am pretty sure that the `values.yaml` file generated by the action that deploys PRs is incompatible with the changes required by the operator. But you are welcome to try it.

2021-06-30 14:36 UTC, rokroskar commented
you could insert a new secret with the correct values _or_ modify the action for this PR _or_ if it's just a few values you need to add you can use the `extra-values` argument to `/deploy`

2021-06-30 16:24 UTC, ableuler commented
ok, quickly trying to deploy this already went pretty far. What's still missing here are some adaptations to the script which creates the renku realm in order to create the necessary client.

2021-06-30 16:27 UTC, ableuler commented
Also, I think it would be nice if the default scope of amalthea wasn't the `default` namespace but the namespace that amalthea itself is deployed in. This seems a more reasonable default, not just for the Renku case.

2021-07-05 06:56 UTC, ableuler commented
See https://github.com/SwissDataScienceCenter/renku/issues/2184 and https://github.com/SwissDataScienceCenter/amalthea/issues/40.

2021-07-14 20:38 UTC, olevski commented
Ok this is ready for review. The other test that persistently failed is now passing. Now there is a new test that fails that never failed before related to dataset search functionality. However this has nothing to do with the notebook service at all. So I think it is just a flaky test. Also this test was passing in earlier reruns of the same or very recent commits.

2021-07-16 16:58 UTC, ableuler reviewed
Can you please also remove all traces in the admin docs about installing the anonymous sessions extension? https://github.com/SwissDataScienceCenter/renku/blob/master/docs/admin/anonymous-sessions.rst

2021-07-16 16:58 UTC, ableuler commented on helm-chart/renku/templates/ingress.yaml
>        - path: /jupyterhub
I think when we merge this PR jupyterhub will actually be completely gone.

2021-07-25 09:42 UTC, olevski commented
Ok the problem with the deployment not working was because we changed the host IP on which the werkzeug server for the git sidecar in renku notebooks was listening to from `0.0.0.0` to `127.0.0.1`. This somehow made the readiness/liveness probes for gitsidecar because the connection to the git sidecar was refused. I tried to put the host in the readiness/liveness probes but this did not help. Only switching the host ip back to `0.0.0.0` seems to work.

2021-08-13 06:45 UTC, ableuler requested changes
The acceptance test for launching a private session seems to be consistently failing with 
![image](https://user-images.githubusercontent.com/13014091/129315729-42f4366c-6938-4ad9-afc6-43e57661f645.png)

I believe the reason for this is that after opening the tab there's first a login loop to the oidc provider happening, so the window named `JupyterLab` doen't show up right after opening the tab.

2021-09-17 09:41 UTC, ableuler submitted a review, later dismissed

2021-09-17 09:58 UTC, rokroskar commented
Aren't we making a release of Renku soon? We probably want to wait with this PR until that release is done?

2021-09-28 09:37 UTC, ableuler commented
> Aren't we making a release of Renku soon? We probably want to wait with this PR until that release is done?

Renku release is out, let's goooo! 🚀

2021-09-29 21:04 UTC, ableuler approved these changes

2021-10-01 12:30 UTC, merged