Updates for Renku 0.9.0
SwissDataScienceCenter/renku pull request #2276
Opened 2021-09-24 09:48 UTC by pameladelgado

Additionally we will include a new version of contributed project templates.
/deploy

2021-09-27 12:07 UTC, ableuler requested changes
Looking forward to having this release in production. Added some minor suggestions. 

One thing I'm trying to remember is if we're missing some necessary changes to the values files which probably should have been added as PRs got merged. I'm thinking on the necessary ingress annotations for embedding GitLab or the sessions in iframes or instructions on how to change the Keycloak theme, but there might be more.

2021-09-27 13:36 UTC, pameladelgado commented
> 
> 
> Looking forward to having this release in production. Added some minor suggestions.
> 
> One thing I'm trying to remember is if we're missing some necessary changes to the values files which probably should have been added as PRs got merged. I'm thinking on the necessary ingress annotations for embedding GitLab or the sessions in iframes or instructions on how to change the Keycloak theme, but there might be more.

Thanks for your feedback. 
Regarding changes in the values file, none should be needed but I've added a section with instructions of configurable items in this version.

2021-09-27 14:33 UTC, ableuler submitted a review, later dismissed

2021-09-27 14:49 UTC, ciyer requested changes
Excited to be seeing this! 🎉

I made some suggestions for things to add/change in the Changelog.

2021-09-27 14:49 UTC, ciyer commented on CHANGELOG.rst
> +
This looks good. I would add a few more lines here:

```suggestion
* **Sessions**: improve functioning and experience of sessions in iframes
* **File Browser**: allow resizing of file-system navigation view

```

2021-09-27 14:49 UTC, ciyer commented on CHANGELOG.rst
> +* **CLI**: Fix `renku rm` failure in specific cases.
User lowercase for consistency:

```suggestion
* **Templates**: template updating issue with  (see this `forum post <https://renku.discourse.group/t/error-during-environment-creation/407/7>`__).
* **Renku core / CLI**: update rdflib 6 and remove rdflib-jsonld which could not be installed with setuptools ``>58.0.2``.
* **CLI**: fix `renku rm` failure in specific cases.
```

2021-09-28 07:52 UTC, ciyer approved these changes
🎉

2021-09-28 08:26 UTC, merged