chore: make Keycloak theme compatible with current Keycloak version
SwissDataScienceCenter/renku pull request #2421
Opened 2022-01-14 12:10 UTC by ciyer

Use updated Keycloak theme

2022-01-14 13:36 UTC, ableuler commented
The ci deployment does not have an identity provider as login option configured. I guess you tested this on a personal dev deployment with an identity provider set up?

2022-01-14 16:24 UTC, rokroskar commented
What is this bit at the bottom? I looked at it with Firefox and Chrome, looks the same 
![image](https://user-images.githubusercontent.com/3353586/149549664-aa907312-1a75-4ccf-a668-fd08f91cb1b4.png)

2022-01-14 16:30 UTC, lorenzo-cavazzi commented
Same thing here

2022-01-14 17:21 UTC, ciyer commented
That's the background that is included with the new Keycloak theme. Sorry didn't catch that since my screen isn't large enough to see that, but I will make a fix.

2022-01-14 17:34 UTC, ciyer commented
Ok, fixed in https://github.com/SwissDataScienceCenter/keycloak-theme/pull/10

You can see it in action if you try to login on this instance: https://sekhar.dev.renku.ch/

2022-01-17 08:41 UTC, rokroskar requested changes

2022-01-17 08:41 UTC, rokroskar commented on helm-chart/renku/values.yaml
> +      image: renku/keycloak-theme:3.0.0
Lets use a new tag, `3.0.1`?

2022-01-17 15:52 UTC, ciyer commented
I have activated two dummy identity providers on the PR deployment. You will not be able to log into RenkuLab using them, but you can see what the buttons look like.

2022-01-17 16:06 UTC, ableuler approved these changes
LGTM!

2022-01-17 17:01 UTC, rokroskar approved these changes

2022-01-17 17:12 UTC, merged