chore: add 0.12.0 release notes
SwissDataScienceCenter/renku pull request #2440
Opened 2022-01-28 17:38 UTC by rokroskar

Release notes for renku version `0.12.0`.

2022-01-28 17:43 UTC, jachro reviewed
👍

2022-01-31 17:11 UTC, ciyer requested changes
This looks good. There are a few more things from the UI side that might be worth mentioning, but it is your call on whether they make sense in the release nodes.

2022-01-31 17:11 UTC, ciyer commented on CHANGELOG.rst
> +
In addition to what is already mentioned above, we have the following on deck for our changelog for the release:

```
* improved display of math formulas in markdown
* more robust autosave infrastructure
* support for project-template-defined parameter validation
* support for icons and description for project templates
* (bug fix) fix problems with dataset "add to project" button
```

The full notes are here: https://github.com/SwissDataScienceCenter/renku-ui/releases

2022-02-09 14:57 UTC, Panaetius submitted a review, later dismissed

2022-02-09 14:57 UTC, jachro approved these changes
Thanks for putting that together

2022-02-09 14:59 UTC, ableuler commented on CHANGELOG.rst
> +earlier iterations, but depending on the number of project it could still take
```suggestion
earlier iterations, but depending on the number of projects it could still take
```

2022-02-09 15:00 UTC, rokroskar commented on CHANGELOG.rst
> +earlier iterations, but depending on the number of project it could still take
🧐

2022-02-09 15:00 UTC, ableuler reviewed
@olevski now all the pieces for the custom CA certificates are included in the upcoming release, right?

2022-02-09 15:01 UTC, olevski commented on CHANGELOG.rst
> +
```suggestion
* Notebooks: https://github.com/SwissDataScienceCenter/renku-notebooks/releases

```

There are mostly bug fixes on the notebook side. And the s3 buckets feature. But the S3 buckets feature is off by default and is not yet supported by the UI. So I do not want to advertise that yet. In the release when the UI fully supports this we can talk about the s3 storage stuff. Same goes with the custom certificates - not all components have releases that include that. So it is better to talk about that in the release when all the components are ready.

2022-02-09 15:04 UTC, olevski commented
> @olevski now all the pieces for the custom CA certificates are included in the upcoming release, right?

No the gateway is still not tagged for a new release because of the issues with its helm chart (which we have addressed with a PR). 

Also some components have relases here that went out before the custom certificates stuff was merged.

2022-02-09 15:06 UTC, olevski commented on CHANGELOG.rst
> +
I guess the alternative to not saying anything we can mention that there is partial support for s3 bucket storage and for custom CA certificates.

2022-02-09 15:09 UTC, olevski commented on CHANGELOG.rst
> +* (bug fix) fix problems with dataset "add to project" button
```suggestion
* (bug fix) fix problems with dataset "add to project" button
* partial support for custom CA certificates
* experimental support for s3 storage in user sessions
```

2022-02-09 15:27 UTC, olevski commented
Looks good to me!

2022-02-09 15:31 UTC, olevski approved these changes

2022-02-09 15:47 UTC, ableuler submitted a review, later dismissed

2022-02-09 23:51 UTC, rokroskar commented
cc @SwissDataScienceCenter/ordes please have a look ☝️

2022-02-10 09:37 UTC, ciyer requested changes
I think we should be consistent in talking about "cloud storage;"  S3 is a bit confusing since it could me AWS S3, it could me the S3 API, which does not have to be hosted on AWS.

2022-02-10 09:37 UTC, ciyer commented on CHANGELOG.rst
> +* experimental support for s3 storage in user sessions
We decided to call this "cloud storage" and should be consistent with the wording.
```suggestion
* experimental support for cloud storage in user sessions
```

2022-02-10 11:58 UTC, Panaetius approved these changes

2022-02-10 12:48 UTC, cmdoret approved these changes
:+1:

2022-02-10 13:00 UTC, merged