Update from auto-update/renku-core-1.2.1
SwissDataScienceCenter/renku pull request #2555
Opened 2022-04-11 19:18 UTC by RenkuBot

This is an automated pull request.

/deploy

2022-04-13 19:10 UTC, Panaetius approved these changes

2022-04-14 06:22 UTC, ciyer requested changes
Small suggestion for the UI section, otherwise LGTM.

2022-04-14 06:22 UTC, ciyer commented on CHANGELOG.rst
> +- UI: improvements in communication with renku-core
This is probably not informative/relevant to most users. I suggest.

```suggestion
- UI: fixes for projects where the default branch is not called `master`.
```

2022-04-14 07:58 UTC, ciyer approved these changes
👍

2022-04-14 08:33 UTC, merged