chore: update arch docs and add mermaid
SwissDataScienceCenter/renku pull request #2566
Opened 2022-05-02 16:11 UTC by rokroskar

Replaces outdated graphviz architecture diagram with a mermaid-based one. Installs & configures mermaid.

addresses #2565

2022-06-07 12:46 UTC, lorenzo-cavazzi requested changes
Oh, I guess it's time for a review... Sorry, this slipped out of my radar :sweat_smile: 

![Screenshot_20220607_141303](https://user-images.githubusercontent.com/43481553/172381447-4b441cca-c708-421a-bd1b-71c8ba960343.png)

Looks great! And the automatically generated graph has surprisingly no arrows overlapping. This won't happen again, we should never ever change it!

The one detail I would modify is the arrow from KG to GitLab. KG is actually the only backend service that gets server-side events from GitLab through the webhook. Not sure if you want to make it explicit here.

Apart from that, just a tiny detail to update on the conf file.

2022-06-07 12:46 UTC, lorenzo-cavazzi commented on docs/conf.py
> +    'sphinxcontrib.mermaid',
```suggestion
    "sphinxcontrib.mermaid",
```

2022-06-13 11:59 UTC, rokroskar commented
@lorenzo-cavazzi I made the arrow between gitlab and kg be bidirectional - if I add a second arrow going in the other direction it completely explodes the neat graph... that goes agains

> we should never ever change it!

2022-06-13 12:47 UTC, lorenzo-cavazzi approved these changes
Lgtm!

2022-06-13 12:50 UTC, merged