docs: release process
SwissDataScienceCenter/renku pull request #2624
Opened 2022-06-24 09:40 UTC by pameladelgado

2022-09-23 08:59 UTC, jachro commented
I've just noticed there's also https://github.com/SwissDataScienceCenter/renku/blob/release-docs/RELEASE-NOTES.md file which seems to be a bit outdated (e.g. mentions `.travis.yaml` file). Do we actually want to keep it?

2022-09-23 13:57 UTC, rokroskar reviewed
I'm not sure the release process belongs in the general renku docs tbh. It's not really a generic feature of the project but rather a specific detail of how our team works.

2022-09-23 13:57 UTC, rokroskar commented on docs/releases.rst
> +* Sprint June 10 - June 30 2022 release: July 5th
this will go stale immediately, i.e. it already has. I suggest we remove dates from here

2022-10-11 10:46 UTC, rokroskar requested changes
Nice, it's getting there :)

2022-10-11 10:46 UTC, rokroskar commented on docs/releases.rst
> +should not usually be needed(by using APi versioning, feature flags etc.).
```suggestion
should not usually be needed (by using APi versioning, feature flags etc.).

```

2022-10-11 10:46 UTC, rokroskar commented on docs/releases.rst
> +Ideally, components would release when there are meaningful changes or so
This sentence is confusing. I think you can just leave it at "the schedule is up to them"

2022-10-11 10:46 UTC, rokroskar commented on docs/releases.rst
> +* Make a Pull Request in renku repository with updates relevant -and adapted- to USERS and ADMINS in the CHANGELOG.md file. Ask ORDES for review when necessary.
```suggestion
* Make a Pull Request in renku repository with updates relevant -and adapted- to USERS and ADMINS in the CHANGELOG.md file. 
```

2022-10-11 10:46 UTC, rokroskar commented on docs/releases.rst
> +* If relevant, notify users on discourse, twitter using visual tools and short sentences. Coordinate with ORDES.
```suggestion
* If relevant, notify users on discourse, twitter using visual tools and short sentences. 

```

2022-10-11 10:46 UTC, rokroskar commented on docs/releases.rst
> +    * For non-breaking changes: create two pull requests in terraform-renku repository with the changes, one for limited and one for renkulab. Important: add the scheduled maintenance label to help a
There is one PR per deployment - but we should say here that limited can be used as a "canary" and others follow ~1 week later

2022-10-26 22:08 UTC, rokroskar approved these changes

2022-10-31 10:50 UTC, merged