chore: prep 0.13.0
SwissDataScienceCenter/renku pull request #2640
Opened 2022-07-04 09:18 UTC by pameladelgado

To be completed with component updates.

2022-07-05 11:55 UTC, pameladelgado commented
@olevski could you please also add the gateway-related updates?

2022-07-05 14:14 UTC, olevski commented
@pameladelgado the updates for notebooks and gateway are in

2022-07-06 06:58 UTC, lorenzo-cavazzi requested changes

2022-07-06 06:58 UTC, lorenzo-cavazzi commented on CHANGELOG.rst
> +- `renku-graph 2.12.9 <https://github.com/SwissDataScienceCenter/renku-graph/releases/tag/2.12.0>`_
```suggestion
- `renku-graph 2.12.0 <https://github.com/SwissDataScienceCenter/renku-graph/releases/tag/2.12.0>`_
```

2022-07-06 07:09 UTC, lorenzo-cavazzi approved these changes

2022-07-06 07:13 UTC, merged