build: unify ui and ui-server charts
SwissDataScienceCenter/renku pull request #2643
Opened 2022-07-04 12:15 UTC by ciyer

Combine the charts into one chart for the UI.

2022-07-21 17:06 UTC, rokroskar commented
@lorenzo-cavazzi can we deploy this? I guess it needs a new values file...

2022-07-22 07:12 UTC, lorenzo-cavazzi commented
Iirc the CI deployments already have the required values to deploy it.
I just triggered a deplyoment

2022-07-22 07:28 UTC, rokroskar commented
? wouldn't that mean that other CI deployments fail since this isn't merged yet?

2022-07-22 07:31 UTC, lorenzo-cavazzi commented
I suppose the CI values file currently has both the old values (`ui` and `uiserver`) and the new values (`ui.server` and `ui.client`)

2022-07-22 07:33 UTC, rokroskar commented
ha, you're probably right... that possibility has never occurred to me 🙈

2022-07-22 07:36 UTC, lorenzo-cavazzi commented
I guess the counts as a reminder to clean up the unnecessary values after merging the PR :grin:

2022-07-22 09:49 UTC, rokroskar requested changes

2022-07-22 09:49 UTC, rokroskar commented on helm-chart/values.yaml.changelog.md
> +## Upgrading to Renku 0.13.1
```suggestion
## Upgrading to Renku 0.15.0
```

2022-07-27 09:14 UTC, lorenzo-cavazzi commented
Already merged through #2665

2022-07-27 09:14 UTC, closed without merging