chore: prepare release 0.15.0
SwissDataScienceCenter/renku pull request #2666
Opened 2022-07-26 12:33 UTC by lorenzo-cavazzi

Prepare release 0.15.0

I'll deploy later once all the components are ready -- mind that this will include the changes from #2665

2022-07-26 13:00 UTC, rokroskar commented on CHANGELOG.rst
> +* **Renku CLI**: fix mergetool issues 🧰
```suggestion
* **Renku CLI**: fix merge-tool issues 🧰
```

2022-07-26 13:49 UTC, olevski requested changes
You can leave that in if you want. 

But it did not trigger a new minor version in the notebooks or Amalthea and I did not call it a feature there. Also not all images were updated. So it is maybe clearer to remove it also because it should not have any effect on end users. The main benefit was less security vulnerabilities.

2022-07-26 13:49 UTC, olevski commented on CHANGELOG.rst
> +* **User sessions**: update base image Dockerfile 🐋
```suggestion
```

2022-07-27 07:26 UTC, olevski submitted a review, later dismissed

2022-07-27 08:39 UTC, olevski approved these changes
🚢

2022-07-27 10:41 UTC, pameladelgado approved these changes
Looks good, great to have the ui charts finally unified 💪 !

2022-07-27 11:34 UTC, merged