docs: add guide on granting gitlab admin role using cli
SwissDataScienceCenter/renku pull request #2710
Opened 2022-10-04 14:06 UTC by wesjdj

Add a docs section on how to grant a GitLab user the Gitlab admin role using the GitLab CLI.

2022-10-04 18:40 UTC, rokroskar requested changes
Thanks, this is much simpler than the previous instructions. Please either replace the previous instructions or merge them together under a joint section.

2022-10-04 18:40 UTC, rokroskar commented on docs/how-to-guides/admin/deploying-renku.rst
> +Grant a user the GitLab admin role using the GitLab CLI
I think this should probably either replace or merge with the section above that is now called "GitLab deployed as part of renku"

2022-10-26 22:18 UTC, rokroskar commented
@wesjdj what's the status here?

2022-11-15 12:49 UTC, wesjdj commented
I'm going to close this PR as I've included this doc change in my wider GitLab docs rework PR #2741

2022-11-15 12:49 UTC, closed without merging