Update from auto-update/renku-graph-2.22.2
SwissDataScienceCenter/renku pull request #2801
Opened 2022-11-15 18:48 UTC by RenkuBot

This is an automated pull request.

/deploy

2022-11-15 20:51 UTC, rokroskar commented on CHANGELOG.rst
> +This minor bugfix release comes with internal changes to the Knowledge Graph and a other bug fixes.
```suggestion
This minor bugfix release comes with internal changes to the Knowledge Graph and a bug fix on the core service.
```

2022-11-16 08:07 UTC, lorenzo-cavazzi requested changes

2022-11-16 08:07 UTC, lorenzo-cavazzi commented on CHANGELOG.rst
> +* **Renku core service**: a bug causing Plan creation date to be after Activity start date
Should we always start these sentences with a verb? I'm not sure we have a fixed rule for that, but that's what we tired to do lately. Feel free to reword any of the suggested sentences

```suggestion
* **Knowledge Graph**: read lineage data from the new dataset in the Triples Store
* **Renku core service**: prevent Plans creation dates from preceding their corresponding Activities
* **Knowledge Graph**: fix wrong Plans creation dates through migration
```

2022-11-16 08:07 UTC, lorenzo-cavazzi commented on CHANGELOG.rst
> +This minor bugfix release comes with internal changes to the Knowledge Graph and a bug fix on the core service.
```suggestion
This minor bugfix release comes with internal changes to the Knowledge Graph and fixes a glitch on the core service.
```

2022-11-16 08:17 UTC, lorenzo-cavazzi approved these changes
Thank you for the quick fix! :rocket:

2022-11-16 15:37 UTC, Panaetius approved these changes

2022-11-16 15:38 UTC, merged