Update from auto-update/renku-graph-2.26.0
SwissDataScienceCenter/renku pull request #2889
Opened 2023-01-06 16:03 UTC by RenkuBot

This is an automated pull request.

/deploy

2023-01-09 14:04 UTC, lorenzo-cavazzi requested changes
I believe version 0.22 has not been released yet -- that info should probably go under 0.22 instead of a new section 0.23

2023-01-09 14:43 UTC, lokijuhy commented
> I believe version 0.22 has not been released yet -- that info should probably go under 0.22 instead of a new section 0.23

This is correct

2023-01-09 16:59 UTC, lorenzo-cavazzi commented
I moved the changelogs to version 0.22, re-phrased the a bit, and added the changes from the UI since they must be merged together for the tests to pass

2023-01-09 17:21 UTC, lokijuhy approved these changes

2023-01-10 09:48 UTC, aledegano approved these changes

2023-01-10 09:48 UTC, merged