Update from auto-update/renku-ui-3.2.0
SwissDataScienceCenter/renku pull request #2954
Opened 2023-02-16 17:27 UTC by RenkuBot

This is an automated pull request.

/deploy

2023-02-17 18:36 UTC, lorenzo-cavazzi commented
@SwissDataScienceCenter/renku-product-management could you review the changelog?
@SwissDataScienceCenter/yat no relevant changes
@SwissDataScienceCenter/renku-devs the changes on the acceptance tests were already reviewed in #2937

2023-02-20 09:22 UTC, lokijuhy requested changes

2023-02-20 09:22 UTC, lokijuhy commented on CHANGELOG.rst
> +one on a recently visited project, or access your datasets. All from a single page.
```suggestion
Renku ``0.24.0`` introduces a new landing page that puts your most used projects, sessions,
and datasets at your fingertips. Quickly pick up where you left off: connect to your
already-running sessions, start a new session on a recently visited project, or access your
datasets- all from a single page!
```

2023-02-20 09:22 UTC, lokijuhy commented on CHANGELOG.rst
> +* 📜 **UI**: Show commit messages on the dropdown when starting a session
```suggestion
* 📜 **UI**: Show commit messages in the commit selection dropdown when
starting a session from a specific commit
```

2023-02-20 09:54 UTC, lokijuhy approved these changes

2023-02-20 13:42 UTC, aledegano approved these changes

2023-02-20 14:10 UTC, merged