chore: vscode extensions in ssh session
SwissDataScienceCenter/renku pull request #3043
Opened 2023-04-23 15:42 UTC by mohammad-alisafaee

Docs for issues in https://github.com/SwissDataScienceCenter/renku-python/issues/3330

2023-05-22 13:12 UTC, rokroskar commented
@mohammad-alisafaee is there a reason this is still a draft? It reads great to me!

2023-05-22 14:25 UTC, Panaetius requested changes
This reads great, just a minor spelling mistake

2023-05-22 14:25 UTC, Panaetius commented on docs/how-to-guides/renkulab/ssh-into-sessions.rst
> +To install extensions that are already installed in you VS Code on the remote
```suggestion
To install extensions that are already installed in your VS Code on the remote
```

2023-05-24 06:36 UTC, Panaetius approved these changes

2023-07-03 07:27 UTC, merged