feat: core-service horizontal scaling
SwissDataScienceCenter/renku pull request #3060
Opened 2023-05-09 09:26 UTC by Panaetius

needed for https://github.com/SwissDataScienceCenter/renku-python/pull/3178

2023-05-16 22:29 UTC, olevski requested changes

2023-05-16 22:29 UTC, olevski commented on helm-chart/renku/requirements.yaml
> +  repository: "https://swissdatasciencecenter.github.io/helm-charts/" #"file:///home/zenon/DEV/ETH/renku-gateway/helm-chart/renku-gateway"
```suggestion
  repository: "https://swissdatasciencecenter.github.io/helm-charts/"
```

2023-05-16 22:29 UTC, olevski commented on ralf.values.yaml
Reminder to remove this from the PR.

2023-05-16 22:29 UTC, olevski commented on helm-chart/renku/requirements.yaml
> +    parent: global.core.versions
So the only reason for this is to then use `global.core.versions` in the renku-gateway helm chart?

2023-06-01 08:18 UTC, olevski approved these changes

2023-07-06 14:23 UTC, aledegano submitted a review, later dismissed

2023-07-06 14:36 UTC, aledegano submitted a review, later dismissed

2023-07-06 16:02 UTC, olevski approved these changes

2023-07-06 17:24 UTC, merged

2023-07-07 12:23 UTC, bethcg reviewed
Looks good !