chore(docs): fix broken links to renku-python
SwissDataScienceCenter/renku pull request #3063
Opened 2023-05-09 14:54 UTC by bethcg

This pull request collects several commits to solve some broken links to renku-python in the documentation.

2023-05-09 14:56 UTC, bethcg reviewed
Solved broken links in the documentation for renku-python

2023-05-22 12:21 UTC, rokroskar commented
@bethcg what's the status here, could we merge it soon?

2023-07-03 09:23 UTC, bethcg commented on docs/reference/templates.rst
> +`renku init docs <https://renku-python.readthedocs.io/en/stable/reference/commands/template.html#set-a-template>`_.
Completed

2023-09-07 07:59 UTC, rokroskar requested changes

2023-09-07 07:59 UTC, rokroskar commented on docs/topic-guides/sessions/customizing-sessions.rst
> +.. _`renku config command`: https://renku-python.readthedocs.io/en/stable/reference/commands/config.html
can't this also use the internal ref?

2024-03-27 12:50 UTC, rokroskar commented
@bethcg I updated this PR and rebased it on the current release branch. We still ahve these broken links in the wild so we should fix them :)

2024-03-27 12:57 UTC, rokroskar approved these changes

2024-03-27 14:32 UTC, Panaetius approved these changes

2024-03-27 14:34 UTC, merged