Update from auto-update/renku-core-2.4.1
SwissDataScienceCenter/renku pull request #3077
Opened 2023-05-15 09:06 UTC by RenkuBot

2023-05-16 09:31 UTC, rokroskar requested changes
Thanks @Panaetius! just some minor fixes

2023-05-19 15:55 UTC, rokroskar submitted a review, later dismissed

2023-05-19 16:43 UTC, aledegano submitted a review, later dismissed

2023-05-22 12:22 UTC, rokroskar commented
@jachro @Panaetius what is this PR waiting for?

2023-05-22 12:36 UTC, Panaetius commented
for https://github.com/SwissDataScienceCenter/renku/pull/3083

Also had to create https://github.com/SwissDataScienceCenter/terraform-renku/pull/1409 to be merged after this is merged so Dev works properly

2023-05-22 13:31 UTC, Panaetius commented
I'd also like to get https://github.com/SwissDataScienceCenter/renku-actions/pull/49 done first so PR deployments still work without setting the `cli_version` value manually

2023-05-23 11:51 UTC, rokroskar submitted a review, later dismissed

2023-05-24 07:28 UTC, aledegano commented on CHANGELOG.rst
> +0.25.7
This should be `0.26.0`, we are adding a significant amount of features here, it's not just a patch release.

2023-05-24 08:27 UTC, rokroskar approved these changes

2023-05-24 08:50 UTC, aledegano approved these changes

2023-05-24 09:14 UTC, merged