fix(gitlab): Set the authorized params GL accept from OAuth to fix upgrade to KeycloakX.
SwissDataScienceCenter/renku pull request #3109
Opened 2023-06-07 12:13 UTC by aledegano

2023-06-07 13:20 UTC, rokroskar commented on helm-chart/README.rst
> +```
isn't this done automatically in `_gitlab.rb.tpl`?

2023-06-07 13:20 UTC, rokroskar commented on helm-chart/README.rst
> +```
ah nevermind, I missed the "independently" part 😆

2023-06-07 14:22 UTC, olevski requested changes

2023-06-07 14:22 UTC, olevski commented on helm-chart/README.rst
> +Upgrading to 0.27.0
Can mention in the release notes (i.e. CHANGELOG.rst) that people should look at both the `values.yaml.changelog.md` and `helm-chart/README.rst` for instructions on how to update.

Currently in `CHANGELOG.rst` we only tell users to look at `values.yaml.changelog.md` but not the helm chart readme. But both are relevant and should be checked.

2023-06-08 07:36 UTC, olevski approved these changes

2023-06-08 12:41 UTC, bethcg approved these changes
Proceed 👍

2023-06-08 12:53 UTC, merged