Update from auto-update/renku-ui-3.12.2
SwissDataScienceCenter/renku pull request #3252
Opened 2023-09-14 14:05 UTC by RenkuBot

This is an automated pull request.\n\n/deploy

2023-09-14 16:24 UTC, li-il-li submitted a review, later dismissed

2023-09-14 16:35 UTC, rokroskar requested changes

2023-09-14 16:35 UTC, rokroskar commented on CHANGELOG.rst
> +- **UI**: do not error on dataset thumbnails point ot an external URL
```suggestion
- **UI**: do not error on dataset thumbnails pointing to an external URL
```

2023-09-15 06:49 UTC, bethcg approved these changes

2023-09-15 06:50 UTC, rokroskar approved these changes

2023-09-15 07:52 UTC, merged