feat: remove internal gitlab
SwissDataScienceCenter/renku pull request #3297
Opened 2023-10-09 19:40 UTC by olevski

This removes the omnibus gitlab helm deployment that is part of Renku.

We mentioned in our docs that we would deprecate this in the future. I think we should really get rid of it because the more we keep it around the more likely it is that someone will start running with it and then be stuck with the same migration problems that we had to go through.

The easiest/most simple demo of Renku should be done against gitlab.com or any other existing gitlab deployment. Deploying gitlab is NOT a simple thing. And combining that with rolling out Renku in one step is just too daunting.

We also really do not update/maintain/test the Gitlab helm chart. So we run the risk of someone deploying it and having problems or security issues because the helm chart is not up to date.

2023-10-31 16:21 UTC, rokroskar requested changes
Thanks @olevski! It will feel good to not be responsible for this anymore :)

2023-10-31 20:17 UTC, olevski commented on CHANGELOG.rst
> +**Features**
Now I dont mention anything like a feature or fix. Just talk about the removal in the first section of the changelog.

2023-10-31 20:18 UTC, olevski commented on CHANGELOG.rst
> +**Features**
I really dont know how else to formulate this. Let me know what you want me to write and I will add it.

2023-10-31 20:19 UTC, olevski commented on scripts/generate-values/base-renku-values.yaml.template
> +  deployCrd: true
Yeah my bad - it was from resolving conflicts or merging other feature branches in this one. The diff makes sense now.

2024-01-30 23:34 UTC, rokroskar commented
@olevski can we refresh this and get it merged?

2024-10-11 19:39 UTC, rokroskar commented
@olevski I rebased this on 0.60.0 and it seems to be all green (https://github.com/SwissDataScienceCenter/renku/pull/3806) - if you agree, I can force-push my branch here and we can get it merged?

2024-10-21 09:38 UTC, olevski reviewed
I cannot approve this because I opened the PR. But I looked through the changes and everything looks good.

2024-10-21 12:46 UTC, aledegano reviewed
It all looks good.
For completeness I would also add to the file `helm-chart/values.yaml.changelog.md` the deletion of the corresponding values and re-iterating that the embedded Gitlab is gone.

2024-12-03 18:03 UTC, rokroskar commented
@aledegano I added the blurb

2024-12-03 20:37 UTC, aledegano approved these changes

2024-12-04 10:37 UTC, Panaetius approved these changes

2024-12-04 10:39 UTC, merged