feat(helm): Make Jena passwords optional in values file.
SwissDataScienceCenter/renku pull request #3389
Opened 2023-11-29 13:50 UTC by aledegano

This commit continues on the topic of making the definition of the secrets in the values files optional, to simplify CI deployments.

As previous similar commits this change supports:

- Existing deployments where the secret is defined will keep working as usual

- New deployments where the secret is defined will keep working as they did before this change

- New deployments where the secret is NOT defined will get 2 random passwords which will be persisted across upgrades/redeployments

The three scenarios have been manually tested.

This PR doesn't change anything to users or admins, therefore I didn't write an entry in the changelog to avoid unnecessary noise, let me know if you would rather have one.

/deploy

2024-10-21 09:48 UTC, rokroskar commented
@aledegano can we get this either merged or closed? Should be rebased on `release-0.60.0` and (re)tested. Also, I don't know if it affects anything for the script that generates values, but perhaps the Jena secrets can be removed from the values template?

2025-02-05 13:36 UTC, aledegano commented
@rokroskar I have finally came back to this and I have:
- Rebased on the latest scheduled release
- Retested (also on my own to really check that it works without specifying the secrets)
- Removed the keys from the values template file

2025-02-05 15:10 UTC, olevski requested changes
This is great Alessandro! Just two small things.

2025-02-05 15:10 UTC, olevski commented on scripts/generate-values/base-renku-values.yaml.template
> -      secret: <use `openssl rand -hex 8 | base64`>
question: Why are these removed? They are not used at all? Because these are not the values you automated in this PR.

2025-02-05 15:10 UTC, olevski commented on CHANGELOG.rst
> +0.64.1
I think it makes sense to add a single line about this change in the changelog.

2025-02-05 15:21 UTC, aledegano commented on CHANGELOG.rst
> +0.64.1
Will do!

2025-02-12 13:29 UTC, olevski approved these changes

2025-02-14 09:48 UTC, aledegano commented
Change of plans: at this moment the job to test the `generate-values.sh` script is stuck because it cannot find a MacOS 11 where to test it. Rather than fixing the test or changing the target I will simply revert the change to the templated values file, because in the following PR that script will be entirely removed (as secrets won't need to be generated out-of-band anymore).

2025-02-14 10:10 UTC, merged