feat: Renku 2.0 namespaces and groups
SwissDataScienceCenter/renku pull request #3538
Opened 2024-03-07 09:48 UTC by olevski

/deploy renku-python=ciyer/rnp-namespaces renku-ui=ciyer/3023-namespaces ciyer/rnp-namespaces

2024-04-08 08:24 UTC, lokijuhy requested changes
Need changelog

2024-04-09 07:23 UTC, lokijuhy approved these changes

2024-04-09 08:49 UTC, lokijuhy approved these changes

2024-04-09 10:12 UTC, aledegano approved these changes

2024-04-09 11:09 UTC, merged