feat: authorization for Renku 2.0 groups and namespaces
SwissDataScienceCenter/renku pull request #3639
Opened 2024-05-23 15:15 UTC by olevski

/deploy

2024-05-24 12:03 UTC, lokijuhy requested changes

2024-05-24 12:03 UTC, lokijuhy commented on CHANGELOG.rst
> +- **Data Services**: Updated the authorization for access to Renku 2.0 namespaces and groups with Authzed DB
Looks like something funny is going on here?

2024-05-24 12:03 UTC, lokijuhy commented on CHANGELOG.rst
> +- **Data Services**: Updated the authorization for access to Renku 2.0 namespaces and groups with Authzed DB
Ooh was this intentional? It looks like a typo. Can we please combine these into one line?
Also, what do you mean by authorization to namespaces? What does that mean distinct from groups? I would expect it to say "...authorization for access to Renku 2.0 projects and groups..."

2024-05-24 12:03 UTC, lokijuhy commented on CHANGELOG.rst
> +- **Data Services**: allow removing tolerations and affinities on resource pool via PATCH requests
```suggestion
- **Data Services**: Allow removing tolerations and affinities on resource pools via PATCH requests
```

2024-05-24 13:23 UTC, olevski commented
@lokijuhy please note that this PR needs also a ui version before it can be complete and merged. This should happen today or Monday. But it will most likely be on Monday.

2024-05-27 06:22 UTC, Panaetius approved these changes

2024-05-27 11:31 UTC, lokijuhy approved these changes

2024-05-27 11:31 UTC, merged