release 0.54.0
SwissDataScienceCenter/renku pull request #3667
Opened 2024-06-10 08:09 UTC by RenkuBot

Release 0.54.0

This PR is auto-generated by [actions/github-script](https://github.com/actions/github-script).

/deploy

2024-06-25 11:59 UTC, leafty requested changes
This branch cannot be deployed in its current state!

The `platform-init` job fails to create the `secret-service-public-key` during the initial phase of `helm install`.

Secret `secret-service-private-key` exists but `secret-service-public-key` does not.

Logs:
```
leafty@fedora ~ $ kubectl -n renku-ci-ui-3220 logs renku-ci-ui-3220-init-renku-platform-rev1-zxfyx-rf6xg
Warning: Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
INFO:root:Initializing Renku platform
INFO:root:Initializing secret service secret
Traceback (most recent call last):
  File "/app/platform-init.py", line 267, in <module>
    main()
  File "/app/platform-init.py", line 262, in main
    set_secret_service_secrets(config)
  File "/app/platform-init.py", line 202, in set_secret_service_secrets
    initialize_private_key(config)
  File "/app/platform-init.py", line 187, in initialize_private_key
    set_public_key(config)
  File "/app/platform-init.py", line 74, in set_public_key
    private_key_rsa = serialization.load_pem_private_key(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 494, in _handle_key_loading_error
    raise ValueError(
ValueError: ('Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).', [<OpenSSLError(code=503841036, lib=60, reason=524556, reason_text=unsupported)>])
```

```
leafty@fedora ~ $ kubectl -n renku-ci-ui-3220 logs renku-ci-ui-3220-init-renku-platform-rev1-zxfyx-sgdhv
Warning: Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens.
INFO:root:Initializing Renku platform
INFO:root:Initializing secret service secret
INFO:root:Initializing data service encryption
```

2024-06-26 06:30 UTC, leafty approved these changes

2024-06-26 09:11 UTC, leafty requested changes

2024-06-26 09:11 UTC, leafty commented on CHANGELOG.rst
> +- `renku-data-services 0.15.0 <https://github.com/SwissDataScienceCenter/renku-data-services/releases/tag/v0.15.0>`
Typo

```suggestion
- `renku-data-services 0.15.0 <https://github.com/SwissDataScienceCenter/renku-data-services/releases/tag/v0.15.0>`__
```

2024-06-26 10:36 UTC, leafty approved these changes

2024-06-26 11:13 UTC, rokroskar commented on CHANGELOG.rst
> +- Test storage credentials before adding cloud storage (`#3194 <https://github.com/SwissDataScienceCenter/renku-ui/pull/3194>`_)
```suggestion
- Test the cloud storage connection before persisting the configuration (`#3194 <https://github.com/SwissDataScienceCenter/renku-ui/pull/3194>`_)
```

2024-06-26 12:43 UTC, rokroskar approved these changes

2024-06-26 12:47 UTC, lorenzo-cavazzi approved these changes

2024-06-26 12:52 UTC, olevski approved these changes

2024-06-26 14:08 UTC, merged