feat: jupyter free sessions in Renku v2
SwissDataScienceCenter/renku pull request #3712
Opened 2024-07-15 11:58 UTC by olevski

/deploy renku-data-services=feat-run-notebook-service

2024-11-18 09:53 UTC, Panaetius requested changes

2024-11-18 09:53 UTC, Panaetius commented on CHANGELOG.rst
> +Therefore it best is most sessions are properly saved and cleaned up before this update is rolled out. In order
```suggestion
Therefore it's best if most sessions are properly saved and cleaned up before this update is rolled out. In order 
```

2024-11-18 09:53 UTC, Panaetius commented on CHANGELOG.rst
> +- **Sessions**: Enable running session images that do not container Jupyter in them.
```suggestion
- **Sessions**: Enable running session images that do not contain Jupyter in them.
```

2024-11-18 09:53 UTC, Panaetius commented on CHANGELOG.rst
> +- **Amalthea**: Brand new operator for sessions with images that do not have to container Jupyter
```suggestion
- **Amalthea**: Brand new operator for sessions with images that do not have to contain Jupyter
```

2024-11-18 09:53 UTC, Panaetius commented on CHANGELOG.rst
> +- **Data services**: Add creation data and created_by for namespaces
```suggestion
- **Data services**: Add creation date and created_by for namespaces
```

2024-11-18 12:34 UTC, Panaetius approved these changes

2024-11-18 16:03 UTC, olevski commented
> Authproxy is broken for anon sessions.

@leafty thatnks for catching that. This small RP fixes the issue: https://github.com/SwissDataScienceCenter/amalthea/pull/768

I forgot to make the authentication middleware act only on the proxy routes - it was acting also on the healthcheck.

2024-11-19 08:03 UTC, leafty approved these changes

2024-11-19 08:23 UTC, merged