release 0.57.2
SwissDataScienceCenter/renku pull request #3782
Opened 2024-09-26 08:42 UTC by RenkuBot

Release 0.57.2

This PR is auto-generated by [actions/github-script](https://github.com/actions/github-script).

/deploy

2024-09-27 07:08 UTC, leafty commented
If this is going to be release, can we include https://github.com/SwissDataScienceCenter/renku-gateway/pull/726?

2024-10-01 12:06 UTC, olevski commented
> If this is going to be released, can we include https://github.com/SwissDataScienceCenter/renku-gateway/pull/726?

@leafty yes, can you do a gateway release and add it here please?

2024-10-02 14:28 UTC, leafty commented
@olevski Why was #3791 merged without testing? The current `HEAD` cannot be deployed:
```
Error: can't get a valid version for repositories csi-rclone. Try changing the version constraint in Chart.yaml
```
https://github.com/SwissDataScienceCenter/renku/actions/runs/11145589990/job/30975547765?pr=3782

2024-10-02 14:39 UTC, olevski commented
> @olevski Why was #3791 merged without testing? The current HEAD cannot be deployed:

Yes we should have tested. I fixed the deployment now.

2024-10-02 15:08 UTC, rokroskar requested changes

2024-10-02 15:08 UTC, rokroskar commented on CHANGELOG.rst
> +
```suggestion
User-facing Changes
~~~~~~~~~~~~~~~~~~~

**Bug Fixes**

- **UI**: show the correct repository access status 
- **Sessions**: allow paused sessions with cloud storage secrets to resume normally

```

2024-10-02 15:08 UTC, rokroskar commented on CHANGELOG.rst
> +
both of the bug fixes were for issues users saw, so I think we should mention it at the top

2024-10-02 15:57 UTC, rokroskar approved these changes

2024-10-02 16:04 UTC, aledegano approved these changes

2024-10-02 17:06 UTC, merged